### PR TITLE
[FEAT]Implemented comment for problems

### LINKED ISSUE #17: Add Comments section for each problem
A comments section is needed for each problem, where users and put up their doubts about the language of the question or point out mistakes in the questions.

### PR DESCRIPTION
**Pull request by divyanshumehta**
Fixed #17 . Commenting feature has been implemented.

### CODE REVIEW

**Review by kumarneetesh24 — CHANGES_REQUESTED** [review]
user image path/url is not correct in comments

**Review by divyanshumehta — COMMENTED** [review]
Made the changes

**Review by kumarneetesh24 — COMMENTED** [review]
Do one thing, remove the image, it will take bandwidth and not looking so nice. Or try to make ui similar to spoj comment ui.

**Comment by divyanshumehta** [comment]
Removed the image

**Pull request merged**
